version: '2'

services:
  umami:
    image: enclaive/umami-sgx
    build: .
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
#    volumes:
#      - "./debug/:/app/debug/"

  mariadb:
    image: enclaive/umami-sgx/mariadb
    build: mariadb
    volumes:
      - type: volume
        target: /data
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"

  nginx:
    image: enclaive/umami-sgx/nginx
    build: nginx
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    ports:
      - '80:80'
      - '443:443'

